-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- CLEANUP: Drop existing tables and triggers to start fresh
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user();
drop table if exists public.reviews cascade;
drop table if exists public.lists cascade;
drop table if exists public.ratings cascade;
drop table if exists public.watchlists cascade;
drop table if exists public.profiles cascade;

-- PROFILES TABLE
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  username text unique,
  avatar_url text,
  settings jsonb default '{"language": "en", "notificationsEnabled": true}'::jsonb,
  top_favorites jsonb default '[]'::jsonb,
  background_theme text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS) for profiles
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Trigger to create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, username, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'avatar_url')
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer set search_path = public;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- WATCHLISTS TABLE
create table public.watchlists (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  show_id bigint not null,
  added_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, show_id)
);

alter table public.watchlists enable row level security;

create policy "Watchlists are viewable by everyone."
  on watchlists for select
  using ( true );

create policy "Users can insert into own watchlist."
  on watchlists for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete from own watchlist."
  on watchlists for delete
  using ( auth.uid() = user_id );

-- RATINGS TABLE
create table public.ratings (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  show_id bigint not null,
  rating integer not null check (rating >= 0 and rating <= 10),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, show_id)
);

alter table public.ratings enable row level security;

create policy "Ratings are viewable by everyone."
  on ratings for select
  using ( true );

create policy "Users can insert/update own ratings."
  on ratings for insert
  with check ( auth.uid() = user_id );

create policy "Users can update own ratings."
  on ratings for update
  using ( auth.uid() = user_id );

create policy "Users can delete own ratings."
  on ratings for delete
  using ( auth.uid() = user_id );

-- LISTS TABLE
create table public.lists (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.profiles(id) not null,
  username text,
  name text not null,
  description text,
  is_private boolean default false,
  items jsonb default '[]'::jsonb,
  likes jsonb default '[]'::jsonb,
  comments jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.lists enable row level security;

create policy "Public lists are viewable by everyone."
  on lists for select
  using ( is_private = false or auth.uid() = user_id );

create policy "Users can create lists."
  on lists for insert
  with check ( auth.uid() = user_id );

create policy "Users can update own lists."
  on lists for update
  using ( auth.uid() = user_id );

create policy "Users can delete own lists."
  on lists for delete
  using ( auth.uid() = user_id );

-- REVIEWS TABLE
create table public.reviews (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.profiles(id) not null,
  username text,
  show_id bigint not null,
  rating integer,
  content text,
  likes jsonb default '[]'::jsonb,
  replies jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.reviews enable row level security;

create policy "Reviews are viewable by everyone."
  on reviews for select
  using ( true );

create policy "Users can create reviews."
  on reviews for insert
  with check ( auth.uid() = user_id );

create policy "Users can update own reviews."
  on reviews for update
  using ( auth.uid() = user_id );

create policy "Users can delete own reviews."
  on reviews for delete
  using ( auth.uid() = user_id );
